# Generated by Django 6.0.5 on 2026-05-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chitietdonhang',
            fields=[
                ('machitiet', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField(blank=True, null=True)),
                ('dongia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('thanhtien', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'chitietdonhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chitietsanpham',
            fields=[
                ('machitiet', models.AutoField(primary_key=True, serialize=False)),
                ('giaban', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('soluongton', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('hinhanh', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'chitietsanpham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donhang',
            fields=[
                ('madonhang', models.AutoField(primary_key=True, serialize=False)),
                ('ngaydat', models.DateTimeField(blank=True, null=True)),
                ('trangthai', models.CharField(blank=True, max_length=50, null=True)),
                ('tongtien', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tongtiensaugiam', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tiengiam', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('diachigiaohang', models.CharField(blank=True, max_length=255, null=True)),
                ('sodienthoainhanhang', models.CharField(blank=True, max_length=15, null=True)),
                ('ghichu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Giohang',
            fields=[
                ('magiohang', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.IntegerField(blank=True, null=True)),
                ('ngaythem', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'giohang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hang',
            fields=[
                ('mahang', models.AutoField(primary_key=True, serialize=False)),
                ('tenhang', models.CharField(max_length=100)),
                ('quocgia', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'hang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khachhang',
            fields=[
                ('makhachhang', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('sodienthoai', models.CharField(blank=True, max_length=15, null=True)),
                ('diachi', models.CharField(blank=True, max_length=255, null=True)),
                ('ngaytao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'khachhang',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Khuyenmai',
            fields=[
                ('makhuyenmai', models.AutoField(primary_key=True, serialize=False)),
                ('tenchuongtrinh', models.CharField(max_length=100)),
                ('mota', models.CharField(blank=True, max_length=255, null=True)),
                ('ngaybatdau', models.DateField(blank=True, null=True)),
                ('ngayketthuc', models.DateField(blank=True, null=True)),
                ('phantramgiam', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('giamtoida', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('soluongsudung', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'khuyenmai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaisanpham',
            fields=[
                ('maloai', models.AutoField(primary_key=True, serialize=False)),
                ('tenloai', models.CharField(max_length=100)),
                ('mota', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'loaisanpham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mausac',
            fields=[
                ('mamau', models.AutoField(primary_key=True, serialize=False)),
                ('tenmau', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'mausac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nhacungcap',
            fields=[
                ('manhacungcap', models.AutoField(primary_key=True, serialize=False)),
                ('tennhacungcap', models.CharField(max_length=100)),
                ('diachi', models.CharField(blank=True, max_length=255, null=True)),
                ('sodienthoai', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nhacungcap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phanhoi',
            fields=[
                ('maphanhoi', models.AutoField(primary_key=True, serialize=False)),
                ('noidung', models.CharField(blank=True, max_length=255, null=True)),
                ('ngayphanhoi', models.DateTimeField(blank=True, null=True)),
                ('danhgia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phanhoi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phanquyen',
            fields=[
                ('maquyen', models.AutoField(primary_key=True, serialize=False)),
                ('tenquyen', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'phanquyen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanpham',
            fields=[
                ('masanpham', models.AutoField(primary_key=True, serialize=False)),
                ('tensanpham', models.CharField(max_length=100)),
                ('mota', models.TextField(blank=True, null=True)),
                ('giagoc', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('hinhanhdaidien', models.CharField(blank=True, max_length=255, null=True)),
                ('cosize', models.BooleanField(blank=True, null=True)),
                ('comau', models.BooleanField(blank=True, null=True)),
                ('ngaytao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sanpham',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('masize', models.AutoField(primary_key=True, serialize=False)),
                ('tensize', models.CharField(max_length=20)),
                ('loaisize', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'size',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taikhoan',
            fields=[
                ('mataikhoan', models.AutoField(primary_key=True, serialize=False)),
                ('tendangnhap', models.CharField(max_length=50, unique=True)),
                ('matkhau', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ngaytao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'taikhoan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thongsovot',
            fields=[
                ('mathongso', models.AutoField(primary_key=True, serialize=False)),
                ('docanbang', models.CharField(blank=True, max_length=50, null=True)),
                ('trongluong', models.CharField(blank=True, max_length=10, null=True)),
                ('docung', models.CharField(blank=True, max_length=50, null=True)),
                ('chieudai', models.CharField(blank=True, max_length=20, null=True)),
                ('succang', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'thongsovot',
                'managed': False,
            },
        ),
    ]
